name: First Workflow

# Este flujo de trabajo se ejecuta manualmente
on:
  issues:
    types: [opened]
    workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1
        run: echo step1

      - name: Step 2
        run: echo step2

  job2:
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - name: Cowsay Step
        uses: mscoutermarsh/cowsays-action@master
        with:
          message: "Hello from job2!"
